### ISSUE TITLE
Can't swap DEUS to USDC

### ISSUE THREAD

**Issue by CodingDavid8** [deusfinance/mobile-app#11]
## Steps to reproduce:

1. Load the app
2. Select DEA as From Token
3. Select USDC as To Token
4. Enter 0.02 as From Amount
5. Click on Swap

## Expected behavior
Appearance of a gas customization screen or a pending transaction.

## Actual behavior
Screen gets stuck in loading behavior. 
![grafik](https://user-images.githubusercontent.com/54584421/111006789-ba0d6700-838d-11eb-8712-e4ad08be314e.png)

Console throws error:
```
E/flutter ( 4453): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'getInWei' was called on null.
E/flutter ( 4453): Receiver: null
E/flutter ( 4453): Tried calling: getInWei
E/flutter ( 4453): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 4453): #1      _ConfirmSwapScreenState.estimateGas
package:deus_mobile/…/swap/confirm_swap.dart:684
E/flutter ( 4453): #2      _ConfirmSwapScreenState.getData
package:deus_mobile/…/swap/confirm_swap.dart:665
E/flutter ( 4453): <asynchronous suspension>
```

**Comment by MoonKnightDev** [comment]
issue solved
