### ISSUE TITLE
Advanced mode of Gas Fee customization freezes

### ISSUE THREAD

**Issue by CodingDavid8** [deusfinance/mobile-app#12]
## Steps to reproduce:

1. Load the app ( & log into wallet with a balance)
2. Leave ETH -> DEUS as the default trading pair.
3. Use 0.02 as from value
4. Click on Swap
5. Click on the 'EDIT' button above the gas fee.
6. In the upper right corner, click on Advanced.

## Expected behavior
I get a new screen where I can customize my GAS limit.

## Actual behavior
Screen gets stuck / the whole UI freezes. 
Console throws no error.

-----
Hint: I commented out the advanced button so it won't delay the launch that much. For bugfixing, you need to uncomment it again, otherwise you won't be able to reproduce the error because the button is missing.
Can you please take care of it?

**Comment by MoonKnightDev** [comment]
this issue was solved.
