### ISSUE TITLE
Swap screen doesn't load on release build

### ISSUE THREAD

**Issue by CodingDavid8** [deusfinance/mobile-app#13]
## Steps to reproduce
1. `flutter build apk`
2. Install the apk on your phone (or an emulator - just be sure that you have a release build of the APK, not a debug build!)
3. Launch the app, create a wallet or import one
4. After confirming, wait until the swap screen loads

## Expected behavior
The swap service should initialize for a few seconds, indicated by a `CircularProgressIndicator`. Afterwards, I can select tokens etc. in order to swap.

## Actual behavior
The CircularProgressIndicator doesn't disappear and just keeps spinning. 

------
I suppose the internet connection or something like that is blocked? Everything worked fine when I tried it out in debug mode. 
On the other hand, I noticed that you integrated `<uses-permission android:name="android.permission.INTERNET"/>`. Any ideas?

**Comment by MoonKnightDev** [comment]
this Issue solved.
internet permission was added to manifest.
